### ISSUE TITLE
Please give me information for commercial use of jGoBoard.

### ISSUE THREAD

**Issue by y-ich** [jokkebk/jgoboard#2]
Hi.

I sent the following E-mail to you on June 15th.
I am afraid that my mail might be recognized as spam one by your mailer.
Could you give me  information for commercial use of jGoBoard?

Thank you.

-- E-mail content
Hello.

Thank your for your nice jGoBoard library.

My name is Ichikawa, Yuji, a private web service developer.
I am developing an Internet Go service on Web, and am going to use jGoBoard.

My service will be free at least for a while but I considered that I need to contact you because it is not a private use such as a blog article, is providing a service.
Could you give me information for commercial use of jGoBoard?

Thank you in advance,

P.S.
I modified demoPlay.html to get numbers of capture stones for an experiment.
I will be glad if you like it.
https://github.com/y-ich/jgoboard/commit/63b1ed5bd3e39b23bcb7736568b0202cf78ab9fa

**Comment by jokkebk** [comment]
Hi,

Apologies for not responding to your initial email, I did flag it upon
receiving, but still forgot about it.

Wonderful to hear you liked the library! The standard license is Creative
Commons non-commercial, so for a free service, you can use it free of
charge. In case you are using jGoBoard as a part of service that includes a
commercial component (e.g. paid subscription options, sponsor or ad revenue
exceeding the $10-20/month one might get from a blog or so), there are two
inexpensive options for a commercial site license:

Annual license for $99/year for sites under $2000 of annual revenue, and
$199 for sites above that level - includes all versions
Perpetual license for $199 for sites under $2000 of annual revenue, and
$399 for sites above that level - includes current version and next two
major revisions (with current version speed one should be OK at least until
2020 :)

In case you need to convert from annual to perpetual, or from "small" to
"large" license, I'm happy to discount the new license with 80 % of earlier
investment (e.g. if you get small annual license now and upgrade later,
you'd get $80 discount).

Hope this helps! Also, I'd be happy to get the link to your service once
you have it online!

Joonas

**Comment by y-ich** [comment]
Thank you for your concrete information!
I will tell you the URL of my service when it opens to public.

**Comment by y-ich** [comment]
Hi, jokkebk-san.

I made my app public.
http://twiigo.meteor.com/

Currently it is a free service and I hope that I will pay license fee to you someday.

**Comment by jokkebk** [comment]
Nice! I registered and am now member #15 :)

Joonas

**Comment by wang869** [comment]
can you tell me how to implement the scoring methods to compute the winner?
