### ISSUE TITLE
capture count

### ISSUE THREAD

**Issue by m0ose** [jokkebk/jgoboard#4]
I was looking at Shusaku’s ear reddening game, and was wondering how the captured stones are counted. I think I noticed an error. At move 298 white captured 23, and at the next move its 31(judging by the info on the right). It changed by 8 stones but I only count 4 captures. Could it be an error in the sgf file?
Here is 2 screen shots
![screen shot 2015-06-24 at 12 35 54 pm](https://cloud.githubusercontent.com/assets/393666/8338416/3588599c-1a6e-11e5-9d81-a7ece82a98f0.png)
![screen shot 2015-06-24 at 12 36 10 pm](https://cloud.githubusercontent.com/assets/393666/8338417/382b4b6e-1a6e-11e5-8ec3-d051d03db52d.png)

**Comment by jokkebk** [comment]
Hi m0ose!
Well noticed. There was a bug in the library -- the captured group is found in two adjacent intersections (above and left), and the captures were added twice because of that. I've fixed this in the latest version.
Joonas
